###############################################################################
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y texlive-full

###############################################################################
install:
  - INPUT_FILE=ClassicThesis.tex
  - OUTPUT_FILE="${INPUT_FILE%.*}.pdf"

###############################################################################
script:
  - pdflatex -halt-on-error -interaction nonstopmode "$INPUT_FILE" &&
    bibtex "${INPUT_FILE%.*}.aux" &&
    pdflatex -halt-on-error -interaction nonstopmode "$INPUT_FILE" &&
    pdflatex -halt-on-error -interaction nonstopmode "$INPUT_FILE"

###############################################################################
after_script:
  - if [ -f "${INPUT_FILE%.*}.log" ];
    then
        mkdir -p shippable;
        cp "${INPUT_FILE%.*}.log" shippable/;
    fi;

###############################################################################
after_success:
  - mkdir -p shippable;
    cp "$OUTPUT_FILE" shippable/;

###############################################################################
# Enable archiving of artifacts on Shippable (does nothing on Travis)
archive: true
