###############################################################################
before_install:
  - travis_retry wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  - export PATH="/opt/texbin:$PATH"

###############################################################################
install:
  - INPUT_FILE="ClassicThesis"

###############################################################################
before_script:
  - OUTPUT_FILE="${INPUT_FILE%.tex}.pdf"

###############################################################################
script:
  - pdflatex -halt-on-error -interaction nonstopmode "$INPUT_FILE" &&
    bibtex "${INPUT_FILE%.tex}" &&
    pdflatex -halt-on-error -interaction nonstopmode "$INPUT_FILE" &&
    pdflatex -halt-on-error -interaction nonstopmode "$INPUT_FILE"

###############################################################################
after_script:
  - if [ -f "${INPUT_FILE%.tex}.log" ];
    then
        mkdir -p shippable;
        cp "${INPUT_FILE%.tex}.log" shippable/;
    fi;

###############################################################################
after_success:
  - mkdir -p shippable;
    cp "$OUTPUT_FILE" shippable/;

###############################################################################
# Enable archiving of artifacts on Shippable (does nothing on Travis)
archive: true
